In [75]:
import numpy as np

# np.sort()
Sorts the Numpy array and returns a Numpy array.

In [76]:
a = np.random.randint(0, 100, 15)
print(a)

[99 21 87 35 33 97 20 95 60  8 92 93 22 66 74]


In [77]:
print(np.sort(a))

[ 8 20 21 22 33 35 60 66 74 87 92 93 95 97 99]


In [78]:
# Sort in decreasing order
print(np.sort(a)[::-1])

[99 97 95 93 92 87 74 66 60 35 33 22 21 20  8]


In [79]:
b = np.random.randint(1, 100, 24).reshape(6,4)
print(b)

[[17 83 75 63]
 [20 10 13 32]
 [41 34 98 36]
 [82 11 28  6]
 [29 75 41 51]
 [39 99 14 84]]


In [80]:
print(np.sort(b, axis=0))
print('\n', np.sort(b, axis=1))
#print('\n', np.sort(b, axis=0, kind='mergesort'))
#print('\n', np.sort(b, axis=1, kind='heapsort'))
#print('\n', np.sort(b, kind='quicksort'))
#print('\n', np.sort(b, axis=0, kind='stable'))

[[17 10 13  6]
 [20 11 14 32]
 [29 34 28 36]
 [39 75 41 51]
 [41 83 75 63]
 [82 99 98 84]]

 [[17 63 75 83]
 [10 13 20 32]
 [34 36 41 98]
 [ 6 11 28 82]
 [29 41 51 75]
 [14 39 84 99]]


In [81]:
# Sort in decreasing order
print(np.sort(b, axis=0)[::-1])
print('\n', np.sort(b, axis=1)[::-1])

[[82 99 98 84]
 [41 83 75 63]
 [39 75 41 51]
 [29 34 28 36]
 [20 11 14 32]
 [17 10 13  6]]

 [[14 39 84 99]
 [29 41 51 75]
 [ 6 11 28 82]
 [34 36 41 98]
 [10 13 20 32]
 [17 63 75 83]]


# np.append()
This function appends the given values along the end of the mentioned axis of the array.

In [82]:
print(a)
np.append(a, 200)

[99 21 87 35 33 97 20 95 60  8 92 93 22 66 74]


array([ 99,  21,  87,  35,  33,  97,  20,  95,  60,   8,  92,  93,  22,
        66,  74, 200])

In [83]:
print(b)
np.append(b, np.zeros((b.shape[0], 1)), axis=1)

[[17 83 75 63]
 [20 10 13 32]
 [41 34 98 36]
 [82 11 28  6]
 [29 75 41 51]
 [39 99 14 84]]


array([[17., 83., 75., 63.,  0.],
       [20., 10., 13., 32.,  0.],
       [41., 34., 98., 36.,  0.],
       [82., 11., 28.,  6.,  0.],
       [29., 75., 41., 51.,  0.],
       [39., 99., 14., 84.,  0.]])

# np.concatenate()
This function concatenates series of arrays along an existing axis.

In [84]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [85]:
print(np.concatenate((c,d)))
print(np.concatenate((c,d), axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


# np.unique()
[Documentation](https://numpy.org/doc/stable/reference/generated/numpy.unique.html)

Returns the sorted unique elements of an array. There are three optional outputs in addition to the unique elements:

*  the indices of the input array that give the unique values
*  the indices of the unique array that reconstruct the input array
*  the number of times each unique value comes up in the input array



In [86]:
e = np.array([1,2,3,4,5,6,6,6,7,7,8,8])
print(e)

[1 2 3 4 5 6 6 6 7 7 8 8]


In [87]:
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7, 8])

# numpy.expand_dims()
Expand the shape of an array.

Insert a new axis that will appear at the axis position in the expanded array shape.

In [88]:
print(a)

[99 21 87 35 33 97 20 95 60  8 92 93 22 66 74]


In [89]:
print(np.expand_dims(a, axis=0))
print(np.expand_dims(a, axis=1))
print(np.expand_dims(a, axis=0).shape)
print(np.expand_dims(a, axis=1).shape)

[[99 21 87 35 33 97 20 95 60  8 92 93 22 66 74]]
[[99]
 [21]
 [87]
 [35]
 [33]
 [97]
 [20]
 [95]
 [60]
 [ 8]
 [92]
 [93]
 [22]
 [66]
 [74]]
(1, 15)
(15, 1)


# np.where()
This fucntions returns the indices of elements in an input array when the given conditions are satisfied

In [90]:
print(a)

[99 21 87 35 33 97 20 95 60  8 92 93 22 66 74]


In [91]:
# find all the elements with values greater than 50
np.where(a>50)

(array([ 0,  2,  5,  7,  8, 10, 11, 13, 14]),)

In [92]:
# replace all the elements with values greater than 50 with 0
np.where(a > 50, 0, a)

array([ 0, 21,  0, 35, 33,  0, 20,  0,  0,  8,  0,  0, 22,  0,  0])

In [93]:
# replace all the even elements with 0
np.where((a % 2 == 0), 0, a)

array([99, 21, 87, 35, 33, 97,  0, 95,  0,  0,  0, 93,  0,  0,  0])

# np.argmax() and np.argmin()
This function returns the index of the maximum or minimum element in a particular axis

In [94]:
print(a)
print(b)

[99 21 87 35 33 97 20 95 60  8 92 93 22 66 74]
[[17 83 75 63]
 [20 10 13 32]
 [41 34 98 36]
 [82 11 28  6]
 [29 75 41 51]
 [39 99 14 84]]


In [95]:
print(np.argmax(a, axis=0))
print(np.argmax(b, axis=0))
print(np.argmax(b, axis=1))

0
[3 5 2 5]
[1 3 2 0 1 1]


In [96]:
print(np.argmin(a, axis=0))
print(np.argmin(b, axis=0))
print(np.argmin(b, axis=1))

9
[0 1 1 3]
[0 1 1 3 0 2]


# np.cumsum() and np.cumprod()
This function computes the cummulative sum and product of the array elements over a given axis

In [97]:
print(a)
print(b)

[99 21 87 35 33 97 20 95 60  8 92 93 22 66 74]
[[17 83 75 63]
 [20 10 13 32]
 [41 34 98 36]
 [82 11 28  6]
 [29 75 41 51]
 [39 99 14 84]]


In [98]:
# np.cumsum() and np.cumprod()
print(np.cumsum(a))
print(np.cumprod(a))
print(np.cumsum(b, axis=0))
print(np.cumprod(b, axis=1))
print(np.cumsum(b, axis=0))
print(np.cumprod(b, axis=1))
print(np.cumsum(b))
print(np.cumprod(b))

[ 99 120 207 242 275 372 392 487 547 555 647 740 762 828 902]
[                  99                 2079               180873
              6330555            208908315          20264106555
         405282131100       38501802454500     2310108147270000
    18480865178160000  1700239596390720000 -7898414199049004544
 -7744415715692135424  5377396828186507264 -7901004335808598016]
[[ 17  83  75  63]
 [ 37  93  88  95]
 [ 78 127 186 131]
 [160 138 214 137]
 [189 213 255 188]
 [228 312 269 272]]
[[     17    1411  105825 6666975]
 [     20     200    2600   83200]
 [     41    1394  136612 4918032]
 [     82     902   25256  151536]
 [     29    2175   89175 4547925]
 [     39    3861   54054 4540536]]
[[ 17  83  75  63]
 [ 37  93  88  95]
 [ 78 127 186 131]
 [160 138 214 137]
 [189 213 255 188]
 [228 312 269 272]]
[[     17    1411  105825 6666975]
 [     20     200    2600   83200]
 [     41    1394  136612 4918032]
 [     82     902   25256  151536]
 [     29    2175   89175 4547925]
 

# np.percentile()
numpy.percentile() compute the q-th percentile of data along the specified axis. A percentile is a measure indicating the value below which a given percentage of observations in a group falls

In [99]:
print(a)

[99 21 87 35 33 97 20 95 60  8 92 93 22 66 74]


In [100]:
print(np.percentile(a, 50))
print(np.percentile(a, 100))
print(np.percentile(a, 0))
print(np.percentile(a, 99))

66.0
99.0
8.0
98.72


# np.histogram()
This function gives the histogram (frequency distribution) of an input array.

In [101]:
print(a)

[99 21 87 35 33 97 20 95 60  8 92 93 22 66 74]


In [102]:
np.histogram(a, bins=[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

(array([1, 0, 3, 2, 0, 0, 2, 1, 1, 5]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

# np.corrcoef()
Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [103]:
salary = np.array([10000, 20000, 30000, 40000])
experience = np.array([1, 7, 6, 9])
np.corrcoef(salary, experience)

array([[1.        , 0.87243973],
       [0.87243973, 1.        ]])

# np.isin()
This function helps us check at once wether multiple items are present in the given array or not

In [104]:
print(a)

[99 21 87 35 33 97 20 95 60  8 92 93 22 66 74]


In [105]:
np.isin(a,[1, 87, 45, 73])

array([False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [106]:
a[np.isin(a,[1, 87, 45, 73])]

array([87])

# np.flip()
This function flips the order of the array in a given axis while preserving the shape of the array

In [107]:
print(a)
print(np.flip(a))
print('\n',b)
print('\n',np.flip(b))

[99 21 87 35 33 97 20 95 60  8 92 93 22 66 74]
[74 66 22 93 92  8 60 95 20 97 33 35 87 21 99]

 [[17 83 75 63]
 [20 10 13 32]
 [41 34 98 36]
 [82 11 28  6]
 [29 75 41 51]
 [39 99 14 84]]

 [[84 14 99 39]
 [51 41 75 29]
 [ 6 28 11 82]
 [36 98 34 41]
 [32 13 10 20]
 [63 75 83 17]]


# np.put()
This function replaces specified elements of an array with given values. The indexing works on the flattened target array.

In [108]:
print(a)

[99 21 87 35 33 97 20 95 60  8 92 93 22 66 74]


In [115]:
np.put(a, [0, 3], [23,37])
print(a)

[23 21 87 37 33 97 20 95 60  8 92 93 22 66 74]


# np.delete()
Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those entries not returned by arr[obj].

In [122]:
print(a)

[23 21 87 37 33 97 20 95 60  8 92 93 22 66 74]


In [123]:
np.delete(a, [0, 1, 3])

array([87, 33, 97, 20, 95, 60,  8, 92, 93, 22, 66, 74])

# Set Functions
* np.union1d()
* np.intersect1d()
* np.setxor1d()
* np.setdiff1d()
* np.in1d()

In [124]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr2 = np.array([1,2,4,5,10,11,20,14])

In [125]:
np.union1d(arr, arr2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 14, 20])

In [126]:
np.intersect1d(arr,arr2)

array([ 1,  2,  4,  5, 10])

In [127]:
np.setxor1d(arr, arr2)

array([ 3,  6,  7,  8,  9, 11, 14, 20])

In [129]:
np.setdiff1d(arr, arr2)

array([3, 6, 7, 8, 9])

In [132]:
np.in1d(arr, 1)

/tmp/ipython-input-132-3431819946.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(arr, 1)


array([ True, False, False, False, False, False, False, False, False,
       False])

In [135]:
print(a)

[23 21 87 37 33 97 20 95 60  8 92 93 22 66 74]


In [136]:
np.clip(a, a_min=25, a_max=75)

array([25, 25, 75, 37, 33, 75, 25, 75, 60, 25, 75, 75, 25, 66, 74])