In [1]:
!pip install numpy pandas matplotlib seaborn scipy

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
b = np.array([1,2,3]) # 1D Numpy array
a = np.array([[1,2,3],[4,5,6]]) # 2D Numpy array
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 3D Numpy array
print(a,'\n')
print(b,'\n')
print(c,'\n')
# print(type(a))

[[1 2 3]
 [4 5 6]] 

[1 2 3] 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 



In [4]:
b = np.array([1,2,3], dtype=float) # 1D Numpy array
a = np.array([[1,2,3],[0,0,6]], dtype=bool) # 2D Numpy array
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]], dtype=complex) # 3D Numpy array
print(a,'\n')
print(b,'\n')
print(c,'\n')

[[ True  True  True]
 [False False  True]] 

[1. 2. 3.] 

[[[ 1.+0.j  2.+0.j  3.+0.j]
  [ 4.+0.j  5.+0.j  6.+0.j]]

 [[ 7.+0.j  8.+0.j  9.+0.j]
  [10.+0.j 11.+0.j 12.+0.j]]] 



In [5]:
np.arange(0, 10, 2) # Works like the range funtion in Python
print(np.arange(0, 10, 2))
np.arange(0, 20, 2).reshape(5,2)

[0 2 4 6 8]


array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [6]:
o = np.ones((3,4))
z = np.zeros((4,3))
r = np.random.random((4,3))
i = np.identity(5)
print(o)
print(z)
print(r)
print(i)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.80165619 0.85761291 0.1509866 ]
 [0.24329594 0.56337249 0.57936419]
 [0.20716511 0.34620828 0.85350631]
 [0.81453623 0.24237405 0.20323427]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
np.linspace(-10, 10, 10) # linearly spaced points

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [8]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8,dtype=complex).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0.+0.j 1.+0.j]
  [2.+0.j 3.+0.j]]

 [[4.+0.j 5.+0.j]
  [6.+0.j 7.+0.j]]]


In [9]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [10]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [11]:
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [12]:
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
16


In [13]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
complex128


In [14]:
print(a1.astype(np.int64))
print(a2.astype(np.int32))
print(a3.astype(np.bool))

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[False  True]
  [ True  True]]

 [[ True  True]
  [ True  True]]]


# Array Operations

In [15]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12, 24).reshape(3,4)
a3 = np.random.random((3,4))

print(a1, "\n")
print(a2, "\n")
print(a3, "\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[0.12394893 0.83908841 0.40761417 0.82823158]
 [0.22353628 0.38954298 0.10902736 0.80178907]
 [0.92325195 0.0177236  0.87316725 0.45036636]] 



In [16]:
# Scalar Operation
# Arithmetic Operation
print(a2 ** 2)
print(a1 * 2)
print(a1 + 2)
print(a2 / 2)
print(a2 % 2)
a3 = np.round(a3 * 100)
a3 = a3.astype(np.int32)
print(a3)

[[144 169 196 225]
 [256 289 324 361]
 [400 441 484 529]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]
[[12 84 41 83]
 [22 39 11 80]
 [92  2 87 45]]


In [17]:
# Relational Operation
print(a2 < 35)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [18]:
ar1 = np.random.random((3,4)) * 100
ar2 = np.random.random((3,4)) * 100
print(ar1, "\n")
print(ar2)

[[17.68237917 76.1089248  94.87076324 74.2658176 ]
 [67.03236231 77.59742062 24.15178636 95.16713362]
 [41.39886504  2.37446969  8.34474043 38.84082641]] 

[[ 3.86004319 26.02821868 11.18134757 16.66321276]
 [72.4776493  33.89567662 27.58285628 37.54006565]
 [69.30880476 85.21852343 61.468876   36.81970931]]


In [19]:
ar1 = np.ceil(ar1)
ar2 = np.floor(ar2)
print(ar1, "\n")
print(ar2)

[[18. 77. 95. 75.]
 [68. 78. 25. 96.]
 [42.  3.  9. 39.]] 

[[ 3. 26. 11. 16.]
 [72. 33. 27. 37.]
 [69. 85. 61. 36.]]


In [20]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

When we mention column and row we mention axis = 1(row) or axis = 0(column)

In [22]:
maxi = np.max(a1, axis=0)
mini = np.min(a1, axis=1)
sum = np.sum(a1, axis=1)
print(mini)
print(maxi)
print(sum)

[0 4 8]
[ 8  9 10 11]
[ 6 22 38]


In [23]:
# Mean
av = np.mean(a1)
# Median
mu = np.median(a2)
# Standard Deviation
sd = np.std(a2)
# Variance
v = np.var(a2)
print(av)
print(mu)
print(sd)
print(v)

5.5
17.5
3.452052529534663
11.916666666666666


In [24]:
# Dot product
product = np.dot(a1, a2.transpose())
print(product)

[[ 86 110 134]
 [302 390 478]
 [518 670 822]]


In [58]:
a5 = np.arange(12).reshape(4,3)
a4 = np.arange(27).reshape(3,3,3)
a6 = np.arange(1, 20, 2)
print(a5)
print(a4)
print(a6)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[ 1  3  5  7  9 11 13 15 17 19]


In [26]:
a5

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
# Indexing
# a4[1,1,0]
a4[2,1,1]
# Slicing
a6[0:4] #?
# a5[0,:1]
a5[:,1]

array([ 1,  4,  7, 10])

In [35]:
a5[1:,1:2]

array([[ 4],
       [ 7],
       [10]])

In [41]:
a5[1,::2]

array([3, 5])

In [49]:
a5[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [51]:
a5[2,::2]

array([6, 8])

In [52]:
a5[0:2,1:3]

array([[1, 2],
       [4, 5]])

In [56]:
a5[0:4:3,1:3]

array([[ 1,  2],
       [10, 11]])

In [59]:
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [65]:
a4[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [67]:
a4[1,:,1]

array([10, 13, 16])

In [64]:
a4[0,1]

array([3, 4, 5])

In [68]:
a4[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [71]:
a4[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [76]:
# Iterating
#a6
for i in a6:
  print(i)

1
3
5
7
9
11
13
15
17
19


In [77]:
#a5
for i in a5:
  print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [80]:
# a4
#for i in a4:
#  print(i)

# Iterates over all the items in 3D array
for i in np.nditer(a4):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [87]:
# Transpose
print(np.transpose(a5))
# Ravel
print(np.ravel(a4))

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [97]:
# Stacking
arr1 = np.arange(12).reshape(3,4)
arr2 = np.arange(12,24).reshape(3,4)
print(arr1)
print(arr2)

# Horizontal Stacking
print(np.hstack((arr1,arr2)))
# Vertical Stacking
print(np.vstack((arr1, arr2)))
# Horizontal Splitting
print(np.hsplit(arr1,2))
# Vertical Spliting
print(np.vsplit(arr2,3))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[12, 13, 14, 15]]), array([[16, 17, 18, 19]]), array([[20, 21, 22, 23]])]
