<a href="https://colab.research.google.com/github/pickle-lotus0976/Learning/blob/main/PyTorch%20Notebooks/NN_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
!sudo apt update

Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:3 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:4 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:5 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:6 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:10 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,257 kB]
Fetched 1,386 kB in 21s (66.7 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
38 packages can be upgraded. Run 'apt list --upgradable'

In [21]:
!pip install torchinfo

In [22]:
# import torch
# import torch.nn as nn

# class Model(nn.Module):
#   def __init__(self, num_features) -> None:
#     super().__init__()

#     self.linear = nn.Linear(num_features, 1)
#     self.sigmoid = nn.Sigmoid()

#   def forward(self, features) -> torch.Tensor:
#     out = self.linear(features)
#     out = self.sigmoid(out)
#     return out

In [23]:
# import torch
# import torch.nn as nn

# class Model(nn.Module):
#   def __init__(self, num_features) -> None:
#     super().__init__()

#     self.linear1 = nn.Linear(num_features, 3)
#     self.relu = nn.ReLU()
#     self.linear2 = nn.Linear(3, 1)
#     self.sigmoid = nn.Sigmoid()

#   def forward(self, features) -> torch.Tensor:
#     out = self.linear1(features)
#     out = self.relu(out)
#     out = self.linear2(out)
#     out = self.sigmoid(out)
#     return out

In [29]:
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features) -> None:
    super().__init__()
    self.network = nn.Sequential(
    nn.Linear(num_features, 3),
    nn.ReLU(),
    nn.Linear(3, 1),
    nn.Sigmoid()
    )

  def forward(self, features) -> torch.Tensor:
    out = self.network(features)
    return out

In [24]:
# creating dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.5798],
        [0.5782],
        [0.5781],
        [0.5809],
        [0.5763],
        [0.5783],
        [0.5762],
        [0.5779],
        [0.5785],
        [0.5788]], grad_fn=<SigmoidBackward0>)

In [25]:
# show model weights
print(model.linear1.weight)
print(model.linear2.weight)

Parameter containing:
tensor([[ 0.4443, -0.3324,  0.0227,  0.0615,  0.1023],
        [-0.0113, -0.2051,  0.2101,  0.0467, -0.1307],
        [-0.2558, -0.1744,  0.4010, -0.4360,  0.3483]], requires_grad=True)
Parameter containing:
tensor([[-0.0433, -0.4865, -0.0825]], requires_grad=True)


In [26]:
# show model bias
print(model.linear1.bias)
print(model.linear2.bias)

Parameter containing:
tensor([ 0.3011, -0.4292, -0.3945], requires_grad=True)
Parameter containing:
tensor([0.3345], requires_grad=True)


In [27]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00