In [2]:
!sudo apt-get update
!sudo apt upgrade

Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:7 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading

In [3]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128

Looking in indexes: https://download.pytorch.org/whl/cu128


In [67]:
import torch
import numpy as np
print(torch.__version__)

2.7.1+cu128


In [5]:
if torch.cuda.is_available():
  print(torch.cuda.get_device_name(0))
  device = torch.device('cuda')
else:
  print('GPU is not available')

Tesla T4


# Creating a Tensor

In [6]:
# using empty
x = torch.empty(2,3) # creates a space in the memory and shows the values that were already there
print(x)
print(type(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>


In [7]:
# using zeros
x = torch.zeros(2,3)
print(x)
y = torch.ones(2,3)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [8]:
# using rand
x = torch.rand(4,4)
print(x)

tensor([[0.9484, 0.0804, 0.8896, 0.2330],
        [0.7135, 0.4080, 0.1827, 0.1710],
        [0.7385, 0.1291, 0.7323, 0.4447],
        [0.1265, 0.1677, 0.0690, 0.3298]])


In [9]:
# using manual_seed (used for reproducibilty)
torch.manual_seed(42)
x = torch.rand(4,4)
print(x)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294]])


In [10]:
torch.manual_seed(42)
x = torch.rand(4,4)
print(x)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294]])


In [11]:
torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
# other methods
# using arange
print("using arange ->\n", torch.arange(0,10,2))
# using linespace
print("\nusing linespace ->\n", torch.linspace(0,10,10))
# using logspace
print("\nusing logspace ->\n", torch.logspace(0,10,10))
# using eye
print("\nusing eye ->\n", torch.eye(5))
# using full
print("\nusing full ->\n", torch.full((3, 3), 5))

using arange ->
 tensor([0, 2, 4, 6, 8])

using linespace ->
 tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

using logspace ->
 tensor([1.0000e+00, 1.2915e+01, 1.6681e+02, 2.1544e+03, 2.7826e+04, 3.5938e+05,
        4.6416e+06, 5.9948e+07, 7.7426e+08, 1.0000e+10])

using eye ->
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

using full ->
 tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shape

In [13]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x.shape

torch.Size([3, 3])

In [14]:
y = torch.empty_like(x)
print(y)

tensor([[167574470,         5,         5],
        [        5,         5,         5],
        [        5,         5,       112]])


In [15]:
print(torch.zeros_like(x))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [16]:
print(torch.ones_like(x))

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [17]:
# print(torch.rand_like(x)) # this will throw an error
#Why?
#Because the tensor x contains only integers and rand_like generates floating point numbers between zero and one

# Tensor Data Types

In [18]:
x.dtype

torch.int64

In [19]:
# assign data type
print(torch.tensor([0.1, 0.2, 0.3]).dtype)
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

torch.float32


tensor([1, 2, 3], dtype=torch.int32)

In [20]:
torch.tensor([1, 2, 3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [21]:
# using to()
print(x, "\n")
x.to(torch.float32)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) 



tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [22]:
print(torch.rand_like(x, dtype=torch.float32))

tensor([[0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414],
        [0.2969, 0.8317, 0.1053]])


# Mathematical Operations

In [23]:
# Scalar operations
print(x, '\n')
print(x + 2, '\n')
print(x - 2, '\n')
print(x * 2, '\n')
print(x / 2, '\n')
print(x % 2, '\n')
print(x // 2, '\n')
print(x ** 2, '\n')

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) 

tensor([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]) 

tensor([[-1,  0,  1],
        [ 2,  3,  4],
        [ 5,  6,  7]]) 

tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]) 

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000],
        [3.5000, 4.0000, 4.5000]]) 

tensor([[1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]]) 

tensor([[0, 1, 1],
        [2, 2, 3],
        [3, 4, 4]]) 

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]]) 



# Elementwise operation

In [24]:
a = torch.rand(3,3)
b = torch.rand(3,3)
print(a, '\n')
print(b, '\n')
print(a + b, '\n')
print(a - b, '\n')
print(a * b, '\n')
print(a / b, '\n')
print(a // b, '\n')
print(a ** b, '\n')

tensor([[0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516],
        [0.0753, 0.8860, 0.5832]]) 

tensor([[0.3376, 0.8090, 0.5779],
        [0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104]]) 

tensor([[0.6071, 1.1678, 0.7773],
        [1.4512, 0.5608, 1.2939],
        [0.7096, 1.2504, 1.2936]]) 

tensor([[-0.0682, -0.4502, -0.3786],
        [-0.3568, -0.5485,  0.6092],
        [-0.5591,  0.5216, -0.1272]]) 

tensor([[0.0910, 0.2903, 0.1152],
        [0.4947, 0.0034, 0.3257],
        [0.0477, 0.3229, 0.4143]]) 

tensor([[0.7982, 0.4435, 0.3450],
        [0.6053, 0.0111, 2.7798],
        [0.1187, 2.4314, 0.8209]]) 

tensor([[0., 0., 0.],
        [0., 0., 2.],
        [0., 2., 0.]]) 

tensor([[0.6423, 0.4364, 0.3938],
        [0.5798, 0.0594, 0.9831],
        [0.1938, 0.9569, 0.6818]]) 



In [25]:
print(a, '\n')
print(b)

tensor([[0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516],
        [0.0753, 0.8860, 0.5832]]) 

tensor([[0.3376, 0.8090, 0.5779],
        [0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104]])


In [26]:
# negetive
torch.neg(a)

tensor([[-0.2695, -0.3588, -0.1994],
        [-0.5472, -0.0062, -0.9516],
        [-0.0753, -0.8860, -0.5832]])

In [27]:
# absolute value
torch.abs(b)

tensor([[0.3376, 0.8090, 0.5779],
        [0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104]])

In [28]:
# round
torch.round(a)

tensor([[0., 0., 0.],
        [1., 0., 1.],
        [0., 1., 1.]])

In [29]:
# ceil
torch.ceil(b)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [30]:
# floor
torch.floor(b)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [31]:
# clamping
torch.clamp(a, min=0, max=0.5)

tensor([[0.2695, 0.3588, 0.1994],
        [0.5000, 0.0062, 0.5000],
        [0.0753, 0.5000, 0.5000]])

# Reduction Operation

In [32]:
c = torch.rand(3,3)
print(c)

tensor([[0.9464, 0.7890, 0.2814],
        [0.7886, 0.5895, 0.7539],
        [0.1952, 0.0050, 0.3068]])


In [33]:
# sum
print(torch.sum(c))
# sum along rows
print(torch.sum(c, dim=0))
# sum along columns
print(torch.sum(c, dim=1))

tensor(4.6560)
tensor([1.9303, 1.3835, 1.3422])
tensor([2.0169, 2.1320, 0.5071])


In [34]:
# mean, median, sd, var
print(torch.mean(c)) # can be applied along both rows and columns
print("\n", torch.median(c))
print("\n", torch.std(c))
print("\n", torch.var(c))
print("\n", torch.mode(c))

tensor(0.5173)

 tensor(0.5895)

 tensor(0.3277)

 tensor(0.1074)

 torch.return_types.mode(
values=tensor([0.2814, 0.5895, 0.0050]),
indices=tensor([2, 1, 1]))


In [35]:
# argmax and argmin
t = torch.randint(size=(3,3), low=10, high=99)
print(t, "\n")
print(torch.argmax(t))
print(torch.argmin(t))

tensor([[39, 52, 12],
        [63, 72, 75],
        [54, 23, 61]]) 

tensor(5)
tensor(2)


In [36]:
print(torch.argmax(t, dim=0))
print(torch.argmax(t, dim=1))
print(torch.argmin(t, dim=0))
print(torch.argmin(t, dim=1))

tensor([1, 1, 1])
tensor([1, 2, 2])
tensor([0, 2, 0])
tensor([2, 0, 1])


In [37]:
# matrix multiplication
vector1 = torch.tensor([[1, 2], [3, 4]])
vector2 = torch.tensor([[5, 6], [7, 8]])
print(vector1, "\n", vector2, "\n")
torch.matmul(vector1, vector2)

tensor([[1, 2],
        [3, 4]]) 
 tensor([[5, 6],
        [7, 8]]) 



tensor([[19, 22],
        [43, 50]])

In [38]:
a = torch.tensor([1, 2])
b = torch.tensor([3, 4])
print(a, "\n", b, "\n")
torch.dot(a, b)

tensor([1, 2]) 
 tensor([3, 4]) 



tensor(11)

In [39]:
# transpose
print(t, "\n")
torch.transpose(t, 0, 1)

tensor([[39, 52, 12],
        [63, 72, 75],
        [54, 23, 61]]) 



tensor([[39, 63, 54],
        [52, 72, 23],
        [12, 75, 61]])

In [40]:
h = torch.randint(size=(3,3), low=0, high=9, dtype=torch.float32)
print(h, '\n')
torch.det(h)

tensor([[3., 2., 7.],
        [0., 5., 6.],
        [1., 7., 7.]]) 



tensor(-44.0000)

In [41]:
torch.inverse(h)

tensor([[ 0.1591, -0.7955,  0.5227],
        [-0.1364, -0.3182,  0.4091],
        [ 0.1136,  0.4318, -0.3409]])

In [42]:
t1 = torch.tensor([[1, 2], [3, 4]])
t2 = torch.tensor([[3, 6], [1, 8]])
print(t1, '\n', t2)
print(t1 > t2, '\n')
print(t1 == t2, '\n')
print(t1 != t2, '\n')
print(t1 >= t2, '\n')

tensor([[1, 2],
        [3, 4]]) 
 tensor([[3, 6],
        [1, 8]])
tensor([[False, False],
        [ True, False]]) 

tensor([[False, False],
        [False, False]]) 

tensor([[True, True],
        [True, True]]) 

tensor([[False, False],
        [ True, False]]) 



# Special Functions

In [43]:
k = torch.randint(size=(3,3), low=0, high=9, dtype=torch.float32)
print(k, '\n')
torch.exp(k)

tensor([[8., 0., 7.],
        [7., 7., 2.],
        [3., 1., 8.]]) 



tensor([[2.9810e+03, 1.0000e+00, 1.0966e+03],
        [1.0966e+03, 1.0966e+03, 7.3891e+00],
        [2.0086e+01, 2.7183e+00, 2.9810e+03]])

In [44]:
torch.log(k)

tensor([[2.0794,   -inf, 1.9459],
        [1.9459, 1.9459, 0.6931],
        [1.0986, 0.0000, 2.0794]])

In [45]:
torch.sigmoid(k)

tensor([[0.9997, 0.5000, 0.9991],
        [0.9991, 0.9991, 0.8808],
        [0.9526, 0.7311, 0.9997]])

In [46]:
torch.relu(k)

tensor([[8., 0., 7.],
        [7., 7., 2.],
        [3., 1., 8.]])

# Inplace Operations

In [47]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)
print(m, '\n')
print(n, '\n')

tensor([[0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035]]) 

tensor([[0.3813, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]]) 



In [48]:
m.add_(n)

tensor([[1.2968, 1.0278, 0.2707],
        [1.0130, 0.9503, 1.4092]])

In [49]:
print(m, '\n', n)

tensor([[1.2968, 1.0278, 0.2707],
        [1.0130, 0.9503, 1.4092]]) 
 tensor([[0.3813, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])


In [50]:
n.relu_()

tensor([[0.3813, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

# Copying a Tensor

In [51]:
# The problem with this approach is that the changes in the original matrix is reflected in the copy
a = torch.rand(3,3)
b = a
print(a, '\n', b, '\n')
print(id(a))
print(id(b))

tensor([[0.3725, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578],
        [0.3313, 0.3227, 0.0162]]) 
 tensor([[0.3725, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578],
        [0.3313, 0.3227, 0.0162]]) 

132760692689904
132760692689904


In [52]:
a[0][0] = 0.0
print(a, '\n', b)

tensor([[0.0000, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578],
        [0.3313, 0.3227, 0.0162]]) 
 tensor([[0.0000, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578],
        [0.3313, 0.3227, 0.0162]])


In [53]:
c = torch.clone(a)

In [54]:
print(a, '\n', c, '\n')
a[0][0] = 0.1
print(a, '\n', c)

tensor([[0.0000, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578],
        [0.3313, 0.3227, 0.0162]]) 
 tensor([[0.0000, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578],
        [0.3313, 0.3227, 0.0162]]) 

tensor([[0.1000, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578],
        [0.3313, 0.3227, 0.0162]]) 
 tensor([[0.0000, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578],
        [0.3313, 0.3227, 0.0162]])


# How to use the GPU

In [55]:
device = torch.device('cuda')

In [56]:
import time
size = 10000

matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"CPU time: {cpu_time:.4f} seconds")

matrix_gpu1 = torch.randn(size, size).to(device=device)
matrix_gpu2 = torch.randn(size, size).to(device=device)

start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time

print(f"GPU time: {gpu_time:.4f} seconds")

CPU time: 16.1893 seconds
GPU time: 0.6980 seconds


# Reshaping Tensors

In [58]:
v = torch.ones(4,4)
v

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [59]:
# reshape
v.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [60]:
# flatten
v.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [62]:
w = torch.rand(2,3,4)
print(w, '\n')
w.permute(2, 0, 1).shape

tensor([[[0.6300, 0.8525, 0.4166, 0.7471],
         [0.3541, 0.5245, 0.0573, 0.0593],
         [0.9238, 0.5029, 0.8779, 0.2181]],

        [[0.1703, 0.1704, 0.2798, 0.4343],
         [0.1277, 0.2554, 0.2712, 0.2154],
         [0.4470, 0.5706, 0.9891, 0.0807]]]) 



torch.Size([4, 2, 3])

In [65]:
# unsqueeze
i = torch.rand(226, 226, 3)
i.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [66]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

In [68]:
arr = np.arange(0, 10, 2)
arr

array([0, 2, 4, 6, 8])

In [69]:
y = torch.from_numpy(arr)
y

tensor([0, 2, 4, 6, 8])

In [73]:
print(t1)
t1.numpy()

tensor([[1, 2],
        [3, 4]])


array([[1, 2],
       [3, 4]])