In [129]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch

In [130]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [131]:
df.shape

(569, 33)

In [132]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [133]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# Train Test Split

In [134]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

# Scaling

In [135]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [136]:
X_train

array([[ 0.82777459,  0.0171557 ,  0.73285877, ..., -0.466771  ,
        -0.63627112, -1.36854362],
       [-0.84540345,  0.11013773, -0.84643979, ..., -1.44934589,
         0.56468799, -1.0650486 ],
       [ 1.3666451 , -0.41521077,  1.3955924 , ...,  1.8838104 ,
         1.36061776,  0.40441908],
       ...,
       [-0.38096257, -0.67323592, -0.43797063, ..., -0.85802393,
        -0.86233401, -1.12685122],
       [-0.86326656,  0.47044312, -0.88932255, ..., -1.09945486,
         0.06860553, -0.73341132],
       [-0.30653294, -0.2245976 , -0.38425889, ..., -0.99114796,
        -1.48400697, -1.25983722]])

In [137]:
y_train

157    B
332    B
45     M
263    M
256    M
      ..
173    B
17     M
69     B
419    B
37     B
Name: diagnosis, Length: 455, dtype: object

In [138]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [139]:
y_train

array([0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,

# From Numpy to Torch Tensors

In [140]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [141]:
X_test_tensor

tensor([[-0.8275, -1.3938, -0.8005,  ..., -0.4400, -1.3035, -0.9205],
        [-0.6340,  0.4983, -0.6476,  ..., -0.6489, -0.7760,  0.0491],
        [ 1.4143,  0.1380,  1.2743,  ...,  0.2232, -0.5735, -1.4982],
        ...,
        [-0.8305, -1.4938, -0.7936,  ...,  0.2600,  0.6448,  0.4210],
        [-1.0627, -0.0224, -1.0427,  ..., -1.2684, -0.1669, -0.4967],
        [ 0.1222,  1.3026,  0.1875,  ...,  0.0869,  0.3999,  0.9811]],
       dtype=torch.float64)

# Defining Model

In [142]:
class MySimpleNN():
  def __init__(self, X) -> None:
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward_pass(self, X) -> torch.Tensor:
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def binary_cross_entropy(self, y_pred, y):
    epsilon = 1e-8
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
    return loss

# Parameters

In [143]:
learning_rate = 0.1
epochs = 100

# Training Pipeline

In [144]:
model = MySimpleNN(X_train_tensor) # Initialize with X_train_tensor
for epoch in range(epochs): # Changed variable name from epochs to epoch
  # forward propagation
  y_pred = model.forward_pass(X_train_tensor)

  # Loss
  loss = model.binary_cross_entropy(y_pred, y_train_tensor)
  print(f'Epoch: {epoch + 1}/{epochs}, Loss: {loss.item()}')
  # Backpropagation
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero grads
  model.weights.grad.zero_()
  model.bias.grad.zero_()

Epoch: 1/100, Loss: 3.232896413011294
Epoch: 2/100, Loss: 3.059673724091425
Epoch: 3/100, Loss: 2.885921952620413
Epoch: 4/100, Loss: 2.70908609500394
Epoch: 5/100, Loss: 2.525448270152269
Epoch: 6/100, Loss: 2.3403606700890442
Epoch: 7/100, Loss: 2.1586909325572314
Epoch: 8/100, Loss: 1.9834638115644154
Epoch: 9/100, Loss: 1.815206387708281
Epoch: 10/100, Loss: 1.6527972983426953
Epoch: 11/100, Loss: 1.5021394859093546
Epoch: 12/100, Loss: 1.365474559939027
Epoch: 13/100, Loss: 1.2450413663909894
Epoch: 14/100, Loss: 1.1426342598295036
Epoch: 15/100, Loss: 1.0589832023790757
Epoch: 16/100, Loss: 0.9932534417348782
Epoch: 17/100, Loss: 0.9430868084249534
Epoch: 18/100, Loss: 0.9052721226971715
Epoch: 19/100, Loss: 0.8765980916705517
Epoch: 20/100, Loss: 0.8544031123149303
Epoch: 21/100, Loss: 0.8367256742877062
Epoch: 22/100, Loss: 0.8222172593795581
Epoch: 23/100, Loss: 0.8099832450562485
Epoch: 24/100, Loss: 0.7994363561857657
Epoch: 25/100, Loss: 0.790187549485563
Epoch: 26/100, Los

In [145]:
with torch.no_grad():
  y_pred = model.forward_pass(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy : {accuracy.item()}")

Accuracy : 0.6315789222717285
