<a href="https://colab.research.google.com/github/pickle-lotus0976/Learning/blob/main/PyTorch%20Notebooks/Training_Pipeline_V2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [159]:
!pip install torchinfo

In [160]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch
import torch.nn as nn

In [161]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [162]:
df.shape

(569, 33)

In [163]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [164]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# Train Test Split

In [165]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

# Scaling

In [166]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [167]:
X_train

array([[-0.39226414, -1.64412199, -0.4468573 , ..., -0.49070943,
        -0.19664981,  0.57325945],
       [-0.33706594, -0.81921054, -0.31192201, ..., -0.19191734,
        -1.41610103, -0.70684026],
       [-1.03721153,  0.15292307, -1.04394596, ..., -0.71917944,
        -0.02693237, -0.36668539],
       ...,
       [ 0.13938168,  0.03140637,  0.1169192 , ..., -0.28035734,
        -0.67437297, -0.52279511],
       [-1.33208612,  0.42166192, -1.32267167, ..., -0.75280506,
        -0.03478966,  0.43467784],
       [-0.76703086, -1.00148559, -0.7567868 , ..., -0.78673777,
        -1.71153509, -0.54251424]])

In [168]:
y_train

418    B
284    B
245    B
391    B
112    B
      ..
154    B
176    B
448    B
66     B
183    B
Name: diagnosis, Length: 455, dtype: object

In [169]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [170]:
y_train

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,

In [171]:
type(y_train.shape)

tuple

# From Numpy to Torch Tensors

In [172]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [173]:
X_test_tensor

tensor([[ 0.6042,  0.3445,  0.7009,  ...,  1.4295,  1.2664,  1.6447],
        [-1.5918, -1.4268, -1.5580,  ..., -0.4465,  0.1302,  1.1353],
        [-0.7118,  1.2349, -0.7273,  ..., -1.0141,  0.5404, -0.9161],
        ...,
        [ 1.8767,  2.0107,  1.8099,  ...,  0.6464, -0.7278, -0.0490],
        [-0.2644,  0.3586, -0.2318,  ...,  0.0599, -0.5298, -0.1333],
        [ 1.9028,  2.3659,  2.0503,  ...,  2.3154,  1.8651,  2.1815]],
       dtype=torch.float64)

# Defining Model

In [174]:
# class MySimpleNN(nn.Module):
#   def __init__(self, num_features) -> None:
#     super().__init__()
#     self.linear = nn.Linear(num_features, 1)
#     self.sigmoid = nn.Sigmoid()

#   def forward(self, features) -> torch.Tensor:
#     out = self.linear(features)
#     out = self.sigmoid(out)
#     return out

#   def binary_cross_entropy(self, y_pred, y):
#     epsilon = 1e-8
#     y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
#     loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
#     return loss

In [175]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features) -> None:
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features) -> torch.Tensor:
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

# Parameters

In [176]:
learning_rate = 0.1
epochs = 1000

# Calling the loss function directly from nn module

In [177]:
# loss function
loss_function = nn.BCELoss()

# Training Pipeline

In [178]:
# model = MySimpleNN(X_train_tensor.shape[1]) # Initialize with X_train_tensor
# model.double() # Cast model parameters to float64
# for epoch in range(epochs): # Changed variable name from epochs to epoch
#   # forward propagation
#   y_pred = model(X_train_tensor)

#   # Loss
#   loss = loss_function(y_pred, y_train_tensor.view(-1,1).double())
#   if epoch % 100 == 0:
#     print(f"Epoch : {epoch}, Loss : {loss.item()}")
#   # Backpropagation
#   loss.backward()

#   # parameters update
#   with torch.no_grad():
#     model.linear.weight -= learning_rate * model.linear.weight.grad
#     model.linear.bias -= learning_rate * model.linear.bias.grad

#   # zero grads
#   model.linear.weight.grad.zero_()
#   model.linear.bias.grad.zero_()

In [181]:
model = MySimpleNN(X_train_tensor.shape[1]) # Initialize with X_train_tensor
model.double() # Casting to float64

# optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(epochs): # Changed variable name from epochs to epoch
  # forward propagation
  y_pred = model(X_train_tensor)

  # Loss
  loss = loss_function(y_pred, y_train_tensor.view(-1,1).double())
  if epoch % 100 == 0:
    print(f"Epoch : {epoch}/{epochs}, Loss : {loss.item()}")

  # clearing the gradients
  optimizer.zero_grad()

  # Backpropagation
  loss.backward()

  # Updating parameters
  optimizer.step()

Epoch : 0/1000, Loss : 0.6791980775680513
Epoch : 100/1000, Loss : 0.11071629113058833
Epoch : 200/1000, Loss : 0.09210714647966066
Epoch : 300/1000, Loss : 0.08394653271416645
Epoch : 400/1000, Loss : 0.07904876274109081
Epoch : 500/1000, Loss : 0.0756658717342004
Epoch : 600/1000, Loss : 0.07313659036875252
Epoch : 700/1000, Loss : 0.07114723495821068
Epoch : 800/1000, Loss : 0.06952648746220165
Epoch : 900/1000, Loss : 0.06817131580637407


In [183]:
with torch.no_grad():
  y_pred = model(X_test_tensor)
  y_pred = (y_pred > 0.6).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy : {accuracy.item()}")

Accuracy : 0.5555555820465088
