<a href="https://colab.research.google.com/github/pickle-lotus0976/Learning/blob/main/PyTorch%20Notebooks/Training_Pipeline_V3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
!pip install torchinfo

In [31]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch
import torch.nn as nn

In [32]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [33]:
df.shape

(569, 33)

In [34]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [35]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# Train Test Split

In [36]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

# Scaling

In [37]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [38]:
X_train

array([[ 0.44276772, -1.25667252,  0.40574498, ...,  0.35132533,
        -0.28993306, -0.76120747],
       [-0.92022383,  0.48897313, -0.84088831, ...,  0.42806484,
         0.09409595,  0.74573984],
       [-0.86295528, -1.4566454 , -0.88354719, ..., -0.91242096,
        -0.07321959, -0.93894998],
       ...,
       [ 1.16148806, -0.09447717,  1.09739866, ...,  0.968311  ,
        -0.14811322, -0.09125496],
       [-0.61956393,  2.10757718, -0.6391905 , ..., -0.66531973,
        -0.72973392, -0.09363278],
       [-1.14643461,  0.07491163, -1.13784381, ..., -1.41491128,
        -1.02452797, -0.95678367]])

In [39]:
y_train

133    B
41     M
153    B
20     B
360    B
      ..
129    M
250    M
317    M
452    B
556    B
Name: diagnosis, Length: 455, dtype: object

In [40]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [41]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,

In [42]:
type(y_train.shape)

tuple

# From Numpy to Torch Tensors

In [43]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [44]:
X_test_tensor

tensor([[-0.4535, -0.2051, -0.5125,  ..., -1.6228, -0.6373, -1.1417],
        [ 1.7685,  0.5266,  1.8098,  ...,  2.3634,  4.2276,  1.1226],
        [-1.0462,  0.2161, -0.9759,  ..., -0.8157, -0.8317,  0.4010],
        ...,
        [ 1.1701,  0.1667,  1.1347,  ...,  1.2077,  0.2519,  0.0098],
        [ 0.0963, -1.9719,  0.0860,  ...,  0.1165, -0.0254, -0.2054],
        [ 0.8522, -0.6756,  0.9856,  ...,  2.1562,  1.8501,  1.3307]],
       dtype=torch.float64)

# Dataset and Dataloader

In [45]:
from torch.utils.data import Dataset, DataLoader
class CustomDataset(Dataset):
  def __init__(self, features, labels) -> None:
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self, idx):
    return self.features[idx], self.labels[idx]

In [46]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [47]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

# Defining Model

In [48]:
# class MySimpleNN(nn.Module):
#   def __init__(self, num_features) -> None:
#     super().__init__()
#     self.linear = nn.Linear(num_features, 1)
#     self.sigmoid = nn.Sigmoid()

#   def forward(self, features) -> torch.Tensor:
#     out = self.linear(features)
#     out = self.sigmoid(out)
#     return out

#   def binary_cross_entropy(self, y_pred, y):
#     epsilon = 1e-8
#     y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
#     loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
#     return loss

In [49]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features) -> None:
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features) -> torch.Tensor:
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

# Parameters

In [50]:
learning_rate = 0.1
epochs = 1000

# Training Pipeline

In [51]:
# model = MySimpleNN(X_train_tensor.shape[1]) # Initialize with X_train_tensor
# model.double() # Cast model parameters to float64
# for epoch in range(epochs): # Changed variable name from epochs to epoch
#   # forward propagation
#   y_pred = model(X_train_tensor)

#   # Loss
#   loss = loss_function(y_pred, y_train_tensor.view(-1,1).double())
#   if epoch % 100 == 0:
#     print(f"Epoch : {epoch}, Loss : {loss.item()}")
#   # Backpropagation
#   loss.backward()

#   # parameters update
#   with torch.no_grad():
#     model.linear.weight -= learning_rate * model.linear.weight.grad
#     model.linear.bias -= learning_rate * model.linear.bias.grad

#   # zero grads
#   model.linear.weight.grad.zero_()
#   model.linear.bias.grad.zero_()

In [52]:
# Define the model
model = MySimpleNN(X_train_tensor.shape[1]) # Initialize with X_train_tensor
model.double() # Casting to float64

# optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# loss function
loss_function = nn.BCELoss()

In [53]:
for epoch in range(epochs): # Changed variable name from epochs to epoch
  for batch_features, batch_labels in train_loader:

    # forward propagation
    y_pred = model(X_train_tensor)

    # Loss
    loss = loss_function(y_pred, y_train_tensor.view(-1,1).double())
    if epoch % 100 == 0:
      print(f"Epoch : {epoch}/{epochs}, Loss : {loss.item()}")

    # clearing the gradients
    optimizer.zero_grad()

    # Backpropagation
    loss.backward()

    # Updating parameters
    optimizer.step()

Epoch : 0/1000, Loss : 0.7167688661412175
Epoch : 0/1000, Loss : 0.5535393012706736
Epoch : 0/1000, Loss : 0.46494138683601544
Epoch : 0/1000, Loss : 0.4093807360737293
Epoch : 0/1000, Loss : 0.3705688200358544
Epoch : 0/1000, Loss : 0.34145946977363273
Epoch : 0/1000, Loss : 0.3185565259110439
Epoch : 0/1000, Loss : 0.29991584007882205
Epoch : 0/1000, Loss : 0.2843571769008609
Epoch : 0/1000, Loss : 0.2711154381580353
Epoch : 0/1000, Loss : 0.2596691645809545
Epoch : 0/1000, Loss : 0.24964865888475787
Epoch : 0/1000, Loss : 0.24078331455802215
Epoch : 0/1000, Loss : 0.23286974516541545
Epoch : 0/1000, Loss : 0.22575163433791612
Epoch : 100/1000, Loss : 0.05563631774052923
Epoch : 100/1000, Loss : 0.05563072451180207
Epoch : 100/1000, Loss : 0.05562513693138338
Epoch : 100/1000, Loss : 0.055619554989601784
Epoch : 100/1000, Loss : 0.0556139786768084
Epoch : 100/1000, Loss : 0.05560840798337685
Epoch : 100/1000, Loss : 0.05560284289970317
Epoch : 100/1000, Loss : 0.05559728341620573
Epo

In [54]:
# with torch.no_grad():
#   y_pred = model(X_test_tensor)
#   y_pred = (y_pred > 0.6).float()
#   accuracy = (y_pred == y_test_tensor).float().mean()
#   print(f"Accuracy : {accuracy.item()}")

In [63]:
# model evaluation using test_loader
model.eval()
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.8).float()

    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)

overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f"Overall Accuracy: {overall_accuracy:.4f}")

Overall Accuracy: 0.9531
